name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Release
        uses: softprops/action-gh-release@v1
